name: Deploy to Test Cluster

on:
  push:
    branches:
      - main

jobs:
  build-push:
    name: Build and Push to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout Akvo composite actions
        uses: actions/checkout@v4
        with:
          repository: akvo/composite-actions
          token: ${{ secrets.GH_PAT }}
          path: composite-actions
          ref: main

      - name: Docker Build Backend
        uses: ./composite-actions/.github/actions/docker-build
        with:
          app-name: "akvo-flow-s3-proxy"
          service-name: "backend"
          dockerfile-location: "backend/Dockerfile"

      - name: Docker Push Backend
        uses: ./composite-actions/.github/actions/docker-push
        with:
          app-name: "akvo-flow-s3-proxy"
          service-name: "backend"
          gcloud-sa:  ${{ secrets.GCLOUD_SERVICE_ACCOUNT_REGISTRY }}
          cluster-name: "test"

  rollout:
    name: Rollout to the server
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout Akvo composite actions
        uses: actions/checkout@v4
        with:
          repository: akvo/composite-actions
          token: ${{ secrets.GH_PAT }}
          path: composite-actions
          ref: main

      - name: Rollout Backend
        uses: ./composite-actions/.github/actions/k8s-rollout
        with:
          app-name: "akvo-flow-s3-proxy"
          deployment-name: "backend-deployment"
          container-name: "backend"
          cluster-name: "test"
          namespace-name: "akvo-flow-s3-proxy-namespace"
          gcloud-sa:  ${{ secrets.GCLOUD_SERVICE_ACCOUNT_K8S }}